import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kylie Facison - Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header id='top'>
        <h1>Kylie Facison</h1>
        <hr class="separator" />
        <h2>Full-Stack Software Developer</h2>
      </header>

      <div id='about'>
        <Image 
          src="/personal/headShotSmall.png" 
          alt="Kylie Facison Headshot" 
          width={350}
          height={285}
        />
        <p style={{ maxWidth:500}}>
        As a Full-Stack developer, I am deeply passionate about the art of problem-solving and find great satisfaction in the process of crafting solutions from the ground up. My inherently open-minded disposition allows me to perceive challenges from multiple perspectives, thereby facilitating effective troubleshooting and coding endeavors.
        <br/>
        <br/>
        Looking ahead, I am committed to fostering diversity within the tech industry, aspiring to create a more inclusive environment where individuals from all backgrounds can access equal opportunities for growth and advancement.
        </p>
      </div>

      <div id='skills'>
        <h2>Skills</h2>
        <div>
        <p>JavaScript</p>
        <p>CSS</p>
        <p>HTML</p>
        <p>Python</p>
        <p>TypeScript</p>
        <p>Java </p>
        <p>C++</p>
        <p>C</p>
        <p>React.js</p>
        <p>Node.js</p>
        <p>Express.js</p>
        <p>Next.js</p>
        <p>SQL</p>
        <p>PostgreSQL </p>
        <p>MongoDB </p>
        <p>Mongoose </p>
        <p>Django </p>
        <p>Git</p>
        <p>GitHub</p>
        <p>MathLab </p>
        </div>
      </div>

      <div id='projects'>
        <h2>Projects</h2>

        <div id='preview'>
          <span id='dec'>
          <h3>Yahtzee</h3>
          <p style={{ maxWidth:365}}>
          I developed a dynamic dice game using HTML, CSS, and JavaScript, where players aim to roll specific combinations of numbers with five dice. Through HTML, I structured the game interface for intuitive user interaction, while CSS styling enhanced visual appeal. JavaScript algorithms simulated dice rolling, validated inputs, and computed scores.
          </p>
          </span>
          <Image 
          src="/screenShots/YahtzeePreview.png" 
          alt="Yahtzee Screenshot" 
          width={600}
          height={285}
          />
          <span id='preLink'>
          <Link href='https://github.com/kfacison/yahtzee_project1' target="_blank">GitHub</Link>
          <Link href='https://kfacison.github.io/yahtzee_project1/' target="_blank">Play Game</Link>
          </span>
        </div>

        <div id='preview'>
          <span id='dec'>
          <h3>Recipe Repo</h3>
          <p style={{ maxWidth:365}}>
          I collaborated on the creation of a social networking application using the MERN (MongoDB, Express.js, React.js, Node.js) stack. This platform enables users to sign in, create posts, and establish connections with other users. The development process involved teamwork and contributions from fellow developers, ensuring a robust and feature-rich user experience. 
          </p>
          </span>
          <Image 
          src="/screenShots/RecipeRepoPreview.png" 
          alt="Recipe Repo Screenshot" 
          width={600}
          height={285}
          />
          <span id='preLink'>
          <Link href='https://github.com/kfacison/Recipe_Repo_Project_2' target="_blank">GitHub</Link>
          <Link href='https://reciperepo-4c11628bb5b7.herokuapp.com/' target="_blank">Visit Site</Link>
          </span>
        </div>

        <div id='preview'>
          <span id='dec'>
          <h3>SpaceBook</h3>
          <p style={{ maxWidth:365}}>
          A social networking app where users can sign in, make posts, and connect with other users. The app uses a MERN Stack developed with the contribution of fellow developers. During the development process, I acted as GitHub manager, assisted my team with merge requests, and maintained the main branch.
          </p>
          </span>
          <Image 
          src="/screenShots/SpaceBookPreview.png" 
          alt="SpaceBook Screenshot" 
          width={600}
          height={285}
          />
          <span id='preLink'>
          <Link href='https://github.com/kfacison/spaceBook-P3' target="_blank">GitHub</Link>
          <Link href='https://space-book-5ba0b58adc3c.herokuapp.com/' target="_blank">Visit Site</Link>
          </span>
        </div>

      </div>

      <div id='contacts'>
        <h2>Contacts</h2>
        <p>Email: kfacison1998@gmail.com</p>
        <div id='contactLink'>
          <div>
            <Link href='https://github.com/kfacison' target="_blank">
              <Image 
              src="/icons/github-mark-white.png" 
              alt="GitHub Icon" 
              width={75}
              height={75}
              />
              GitHub
            </Link>
          </div>

          <div>
            <Link href='https://www.linkedin.com/in/kyliefacison1998' target="_blank">
              <Image 
              src="/icons/linkedin-white.png" 
              alt="LinkedIn Icon" 
              width={75}
              height={75}
              />
              LinkedIn
            </Link>
          </div>

          <div>
            <Link href='/personal/Kylie_Facison_Resume 2.1.1(2024).pdf' target="_blank">
            <Image 
            src="/icons/resume-2-white.png" 
            alt="Resume Icon" 
            width={55}
            height={75}
            />
              Resume
            </Link>
          </div>
        </div>
      </div>

    </>
  )
}
