import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kylie Facison - Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 id='home'>Kylie&apos;s Portfolio</h1>
      <div id='about'>
        <h2>About Me</h2>

        <p style={{ maxWidth:650}}>
          As a Full-Stack developer, I love problem-solving, and the challenge of building something from scratch.
          My open-minded nature and capacity to see various viewpoints help me problem-solve and troubleshoot when coding. 
          In the future, I want to contribute to the tech industry&apos;s diversity so that other people can have equal opportunities. </p>

        <Image 
          src="/headShot.png" 
          alt="cool pic"
          width={350}
          height={300}
        />
      </div>
    </>
  )
}
