import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Kylie Facison - Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 id='top'>Kylie&apos;s Portfolio</h1>
      <div id='about' className="">
        <h2>About Me</h2>

        <p style={{ maxWidth:650}}>
          As a Full-Stack developer, I love problem-solving, and the challenge of building something from scratch.
          My open-minded nature and capacity to see various viewpoints help me problem-solve and troubleshoot when coding. 
          In the future, I want to contribute to the tech industry&apos;s diversity so that other people can have equal opportunities. </p>

        <Image 
          src="/headShot.png" 
          alt="cool pic"
          width={350}
          height={300}
        />
      </div>

      <div id='skills'>
        <h2>Skills</h2>
        <ul>
          <li>JavaScript</li>
          <li>CSS</li>
          <li>HTML</li>
          <li>Python</li>
          <li>Java </li>
          <li>C++</li>
          <li>C</li>
          <li>React </li>
          <li>Node.js</li>
          <li>Express.js</li>
          <li>SQL</li>
          <li>Postgresql </li>
          <li>Mongoose </li>
          <li>Django </li>
          <li>Next.js</li>
          <li>Git</li>
          <li>GitHub</li>
          <li>MathLab </li>
          <li>MongoDB </li>
          <li>EJS</li>
          <li>TypeScript</li>
        </ul>
        <p>Work in progress</p>
      </div>

      <div id='projects'>
        <h2>Projects</h2>
        <p>Work in progress</p>
      </div>

      <div id='contacts'>
        <p>Work in progress</p>
      </div>

    </>
  )
}
